language: cpp

compiler:
- gcc
- clang

dist: xenial

matrix:
  include:
  - os: osx
    compiler: clang
    before_install: true
    install: true
    before_script: export ICU_ROOT=$(brew --prefix icu4c)

before_install: |
  cd ~ &&
  wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2 -O - |
    tar -xj &&
  cd -

install: |
  cd ~/boost_1_64_0 &&
  ./bootstrap.sh --with-libraries=locale --with-toolset="$CC" &&
  ./b2 -d0 -j 4 cxxflags=-std=c++14 define=BOOST_LOCALE_HIDE_AUTO_PTR &&
  cd -

before_script: |
  export BOOST_ROOT=~/boost_1_64_0 &&
  export LD_LIBRARY_PATH=$BOOST_ROOT/stage/lib

script: mkdir build && cd build && cmake .. && make -j 4 && ctest -j 4

after_failure:
- cat Testing/Temporary/LastTest.log

addons:
  apt:
    packages:
    - libicu-dev
  homebrew:
    packages:
    - icu4c
    - boost
