language: cpp

compiler:
  - clang
  - gcc

sudo: false

os:
  - linux
#  - osx

before_install: |
  cd ~ &&
  wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2 -O - |
  tar -xj &&
  cd -

install: |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew link icu4c --force
  fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    echo 'using gcc : : g++-5 : ;' > ~/user-config.jam
  fi
  export BOOST_ROOT=~/.local
  cd ~/boost_1_66_0 &&
    ./bootstrap.sh --prefix=$BOOST_ROOT --with-libraries=locale --with-toolset="$CC" &&
    ./b2 install -d0 -j 4 cxxflags=-std=c++14 &&
  cd -

before_script: |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export LD_LIBRARY_PATH=$BOOST_ROOT/lib ;
  fi
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export DYLD_LIBRARY_PATH=$BOOST_ROOT/lib ;
  fi
  # Don't use real gcc on OS X, use only clang
  if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CXX="g++-5" CC="gcc-5";
  fi
  export CXXFLAGS='-g -O2 -Wno-deprecated-declarations'

# -no-deprecated for auto_ptr in boost locale. In 1.67 it is solved better with
# defining a preprocessor variable. Once 1.67 goes public will switch.

script: autoreconf -i && ./configure && make -j 4 && make check -j 4

after_failure:
  - cat tests/hun2/test-suite.log
  - cat tests/v1cmdline/test-suite.log
  - cat tests/test-suite.log

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - gcc-5
    - g++-5
    - libicu-dev
