language: cpp

compiler:
- gcc
- clang

dist: xenial

matrix:
  include:
  - os: osx
    compiler: clang
    before_install: true
    install: true
    before_script: export ICU_ROOT=$(brew --prefix icu4c)
  - os: windows
    # This should be added to PATH as on local Git Bash install, but it isn't
    # on travis. xz is there
    env: PATH="/mingw64/bin:$PATH"
    before_install:
    - echo "$PATH"
    - ls -al /bin
    - ls -al /usr/bin
    - ls -al /mingw64/bin
    - ls -al /c/ProgramData/chocolatey/bin
    - tar --help
    - which tar xz bzip2 gzip 7z git
    - cygpath -w / /bin /usr/bin /mingw64/bin
    install: curl -L https://github.com/nuspell/misc-nuspell/releases/download/v1/vcpkg-export.tar.xz | tar -xJ
    before_script: mkdir build && cd build
    script: |
      cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg-export/scripts/buildsystems/vcpkg.cmake -A Win32 &&
      cmake --build . -j &&
      ctest -C Debug

before_install: |
  cd ~ &&
  wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2 -O - |
    tar -xj &&
  cd -

install: |
  cd ~/boost_1_64_0 &&
  ./bootstrap.sh --with-libraries=locale --with-toolset="$CC" &&
  ./b2 -d0 -j 4 cxxflags=-std=c++14 define=BOOST_LOCALE_HIDE_AUTO_PTR &&
  cd -

before_script: |
  export BOOST_ROOT=~/boost_1_64_0 &&
  export LD_LIBRARY_PATH=$BOOST_ROOT/stage/lib

script: mkdir build && cd build && cmake .. && make -j 4 && ctest -j 4

after_failure:
- cat Testing/Temporary/LastTest.log

addons:
  apt:
    packages:
    - libicu-dev
  homebrew:
    packages:
    - icu4c
    - boost
