language: cpp

os: [ linux, osx ]

dist: bionic
osx_image: xcode11.3

env:
  global:
  - CTEST_PARALLEL_LEVEL=5
  matrix:
  - CXXFLAGS=
  - CXXFLAGS=-fsanitize=address
  - CXXFLAGS=-fsanitize=undefined
  - CXXFLAGS="-Wall -Wextra -Werror"
  - CONFIGURE_ARGS="-DCMAKE_BUILD_TYPE=Release"

matrix:
  include:
  - os: linux
    env: CXXFLAGS="-D_GLIBCXX_DEBUG -O1"
  - os: windows
    env: CTEST_ARGS="-C Debug"
  - os: windows
    env: BUILD_ARGS="--config Release" CTEST_ARGS="-C Release"

addons:
  apt:
    packages: [ libicu-dev ]
  homebrew:
    packages: [ icu4c ]

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = windows ]; then
    # This should be added to PATH as on local Windows Git Bash install,
    # but it isn't on travis. xz is there
    PATH="/mingw64/bin:$PATH"
    curl -L https://github.com/nuspell/misc-nuspell/releases/download/v1/vcpkg-export.tar.xz | tar -xJ
  fi

install:
- |
  if [ "$TRAVIS_OS_NAME" = linux ]; then
    export CMAKE_BUILD_PARALLEL_LEVEL=4
  fi
- |
  if [ "$TRAVIS_OS_NAME" = osx ]; then
    export ICU_ROOT=$(brew --prefix icu4c)
    export CMAKE_BUILD_PARALLEL_LEVEL=4
  fi
- |
  if [ "$TRAVIS_OS_NAME" = windows ]; then
    CONFIGURE_ARGS+=" -DCMAKE_TOOLCHAIN_FILE=../vcpkg-export/scripts/buildsystems/vcpkg.cmake -A Win32"
  fi

script:
- mkdir build
- cd build
- cmake .. $CONFIGURE_ARGS
- cmake --build . $BUILD_ARGS
- ctest $CTEST_ARGS

after_failure: cat Testing/Temporary/LastTest.log
