language: cpp

compiler:
  - clang
  - gcc

sudo: false

os:
  - linux
#  - osx

before_install:
# Don't use real gcc on OS X, use only clang
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CXX="g++-5" CC="gcc-5";
    fi
  - cd ~ &&
    wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.bz2/download -O - |
    tar -xj

install:
  - export BOOST_ROOT=~/.local
  - "cd ~/boost_1_62_0 &&
    echo 'using gcc : : g++-5 ;' > user-config.jam &&
    ./bootstrap.sh --prefix=$BOOST_ROOT --with-libraries=locale &&
    ./b2 install"

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export LD_LIBRARY_PATH=$BOOST_ROOT/lib ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export DYLD_LIBRARY_PATH=$BOOST_ROOT/lib ;
    fi

script:
  - autoreconf -i && ./configure && make && make check

after_failure:
  - cat tests/hun2/test-suite.log
  - cat tests/v1cmdline/test-suite.log
  - cat tests/test-suite.log

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - gcc-5
    - g++-5
    - libicu-dev
